### ISSUE TITLE
grunt build

### ISSUE THREAD

**Issue by ceeroover** [bryanforbes/generator-dojo#2]
I followed the instructions under Getting started.

```
npm install -g yo generator-dojo
mkdir dojo03 && cd $_
yo dojo dojo03
grunt server
grunt build
```

Regardless if I choose Shrinksafe, Closure oder Uglify the build stops with:

```
Building Dojo...
Error
Warning: Task "dojo:dist" failed. Use --force to continue.
```

using --force does not help.

The server seems to work:

```
grunt server
curl localhost:8888
```

results in

```
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <title>Dojo Application</title>

        <link rel="stylesheet" href="dojo03/resources/main.css">
</head>
<body class="claro">
        <script src="dojoConfig.js"></script>
        <script src="dojo/dojo.js" async></script>
</body>
</html>
```

Errors in build-report.txt:

```
error(307) Failed to evaluate module tagged as pure AMD (fell back to processing with regular expressions).
    module: dojo03/tests/dojoConfig; error: ReferenceError: location is not defined
error(356) The optimizer threw an exception; the module probably contains syntax errors.
    module identifier: dojo/dojo; exception: TypeError: object is not a function
    module identifier: dojo03/main; exception: TypeError: object is not a function
```

**Comment by bryanforbes** [comment]
Thanks for the report. This is a result of the `tests` directory being copied during the build, which shouldn't be happening, and has been fixed by a430e29529fc78d372a82d02ea1b3939533bb311. I'll try and do a bug-fix release in the next day to alleviate the problem. In the meantime, you can edit the generated `src/<appname>/package.js` and change `\/test\/` to `\/tests\/` on line 38.

**Comment by lukemarsh** [comment]
Hey, I'm getting the same error when running grunt build and grunt server

Building Dojo...

> > Error
> > Warning: Task "dojo:dist" failed. Use --force to continue.

Aborted due to warnings.

I have changed test to tests on line 38 of the package.js file but it doesn't seem to fix it. any ideas?

**Comment by lukemarsh** [comment]
Any help on this would be greatly appreciated

**Comment by ceeroover** [comment]
Still not working for me too.

**Comment by bryanforbes** [comment]
Sorry for the delay on this. I'll do a bug fix release this afternoon. Can you test master to see if the problem still exists there?

**Comment by ceeroover** [comment]
works now, thanks

**Comment by bryanforbes** [comment]
I have released 0.2.1 with the fix. Thanks for testing it out!
